name:                HaskellLab4
version:             0.1.0.0
github:              "89netram/HaskellLab4"
author:              "Julia Jansson & Mårten Åsberg"
copyright:           ""

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         ""

executables:
  HaskellLab4:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - mnist-idx
    - matrix
    - vector
